export const ROOT = 'SequenceEditPage/';

export const FETCH_SEQUENCE = ROOT + 'FETCH_SEQUENCE';
export const FETCH_SEQUENCE_PENDING = ROOT + 'FETCH_SEQUENCE_PENDING';
export const FETCH_SEQUENCE_FULFILLED = ROOT + 'FETCH_SEQUENCE_FULFILLED';
export const FETCH_SEQUENCE_REJECTED = ROOT + 'FETCH_SEQUENCE_REJECTED';

export const FETCH_SEQUENCE_STAGE = ROOT + 'FETCH_SEQUENCE_STAGE';
export const FETCH_SEQUENCE_STAGE_PENDING = ROOT + 'FETCH_SEQUENCE_STAGE_PENDING';
export const FETCH_SEQUENCE_STAGE_FULFILLED = ROOT + 'FETCH_SEQUENCE_STAGE_FULFILLED';
export const FETCH_SEQUENCE_STAGE_REJECTED = ROOT + 'FETCH_SEQUENCE_STAGE_REJECTED';

export const FETCH_REFERENCE_DATA = ROOT + 'FETCH_REFERENCE_DATA';
export const FETCH_REFERENCE_DATA_PENDING = ROOT + 'FETCH_REFERENCE_DATA_PENDING';
export const FETCH_REFERENCE_DATA_FULFILLED = ROOT + 'FETCH_REFERENCE_DATA_FULFILLED';
export const FETCH_REFERENCE_DATA_REJECTED = ROOT + 'FETCH_REFERENCE_DATA_REJECTED';

export const FETCH_RENDER_PREVIEW_DATA = ROOT + 'FETCH_RENDER_PREVIEW_DATA';
export const FETCH_RENDER_PREVIEW_DATA_PENDING = ROOT + 'FETCH_RENDER_PREVIEW_DATA_PENDING';
export const FETCH_RENDER_PREVIEW_DATA_FULFILLED = ROOT + 'FETCH_RENDER_PREVIEW_DATA_FULFILLED';
export const FETCH_RENDER_PREVIEW_DATA_REJECTED = ROOT + 'FETCH_RENDER_PREVIEW_DATA_REJECTED';

export const SAVE_SEQUENCE = ROOT + 'SAVE_SEQUENCE';
export const SAVE_SEQUENCE_PENDING = ROOT + 'SAVE_SEQUENCE_PENDING';
export const SAVE_SEQUENCE_FULFILLED = ROOT + 'SAVE_SEQUENCE_FULFILLED';
export const SAVE_SEQUENCE_REJECTED = ROOT + 'SAVE_SEQUENCE_REJECTED';

export const ADD_CHANNEL = ROOT + 'ADD_CHANNEL';
export const SHOW_ADD_CHANNEL_MODAL = ROOT + 'SHOW_ADD_CHANNEL_MODAL';
export const HIDE_ADD_CHANNEL_MODAL = ROOT + 'HIDE_ADD_CHANNEL_MODAL';
export const SELECT_EFFECT = ROOT + 'SELECT_EFFECT';
export const ADD_EFFECT = ROOT + 'ADD_EFFECT';
export const COPY_EFFECT = ROOT + 'COPY_EFFECT';
export const PASTE_EFFECT = ROOT + 'PASTE_EFFECT';
export const UPDATE_EFFECT = ROOT + 'UPDATE_EFFECT';
export const DELETE_EFFECT = ROOT + 'DELETE_EFFECT';
export const SELECT_FRAME = ROOT + 'SELECT_FRAME';
