rootProject.name = "sparkled"
include("common")
include("model")
include("music-player")
include("persistence")
include("liquibase")
include("renderer")
include("api")
include("scheduler")
include("udp-server")
include("webui")
