micronaut:
  application:
    name: sparkled

  router:
    static-resources:
      default:
        paths:
          - classpath:webui

  server:
    maxFileSize: 30mb
    maxRequestSize: 30mb
    multipart:
      maxFileSize: 30mb
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:sqlite:sparkled.db
    driverClassName: org.sqlite.JDBC
    data-source-properties:
      foreign_keys: true

jackson:
  deserialization:
    fail-on-unknown-properties: false
    read-unknown-enum-values-using-default-value: true
  serialization-inclusion: NON_NULL # Include empty arrays in JSON output
  serialization:
    order-map-entries-by-keys: true
    write-dates-as-timestamps: false # Write dates as ISO 8601 strings instead of arrays.
  mapper:
    sort-properties-alphabetically: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
