micronaut:
  application:
    name: sparkled

  router:
    static-resources:
      default:
        paths:
          - classpath:webui

  security:
    intercept-url-map:
      - pattern: /**
        httpMethod: GET
        access:
          # Enable access to static webui resources.
          - isAnonymous() # TODO this will prevent API calls from being secured in the future.

  server:
    max-file-size: 20971520 # 30MB
    max-request-size: 20971520 # 30MB
    multipart:
      max-file-size: 20971520 # 30MB
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:sqlite:sparkled.db
    driver-class-name: org.sqlite.JDBC
    data-source-properties:
      foreign_keys: true

jackson:
  deserialization:
    fail-on-unknown-properties: false
    read-unknown-enum-values-using-default-value: true
  serialization-inclusion: NON_NULL # Include empty arrays in JSON output
  serialization:
    order-map-entries-by-keys: true
    write-dates-as-timestamps: false # Write dates as ISO 8601 strings instead of arrays.
  mapper:
    sort-properties-alphabetically: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.xml'
