export const ADD_SCHEDULED_SEQUENCE = 'Scheduler/ADD_SCHEDULED_SEQUENCE';
export const DELETE_SCHEDULED_SEQUENCE = 'Scheduler/DELETE_SCHEDULED_SEQUENCE';
export const FETCH_SCHEDULED_SEQUENCES = 'Scheduler/FETCH_SCHEDULED_SEQUENCES';
export const SHOW_ADD_MODAL = 'Scheduler/SHOW_ADD_MODAL';
export const HIDE_ADD_MODAL = 'Scheduler/HIDE_ADD_MODAL';
export const SHOW_DELETE_MODAL = 'Scheduler/SHOW_DELETE_MODAL';
export const HIDE_DELETE_MODAL = 'Scheduler/HIDE_DELETE_MODAL';
