export const ROOT = 'SchedulerPage/'

export const ADD_SCHEDULED_JOB = ROOT + 'ADD_SCHEDULED_JOB'
export const ADD_SCHEDULED_JOB_PENDING = ROOT + 'ADD_SCHEDULED_JOB_PENDING'
export const ADD_SCHEDULED_JOB_FULFILLED = ROOT + 'ADD_SCHEDULED_JOB_FULFILLED'
export const ADD_SCHEDULED_JOB_REJECTED = ROOT + 'ADD_SCHEDULED_JOB_REJECTED'

export const DELETE_SCHEDULED_JOB = ROOT + 'DELETE_SCHEDULED_JOB'
export const DELETE_SCHEDULED_JOB_PENDING =
  ROOT + 'DELETE_SCHEDULED_JOB_PENDING'
export const DELETE_SCHEDULED_JOB_FULFILLED =
  ROOT + 'DELETE_SCHEDULED_JOB_FULFILLED'
export const DELETE_SCHEDULED_JOB_REJECTED =
  ROOT + 'DELETE_SCHEDULED_JOB_REJECTED'

export const FETCH_SCHEDULED_JOBS = ROOT + 'FETCH_SCHEDULED_JOBS'
export const FETCH_SCHEDULED_JOBS_PENDING =
  ROOT + 'FETCH_SCHEDULED_JOBS_PENDING'
export const FETCH_SCHEDULED_JOBS_FULFILLED =
  ROOT + 'FETCH_SCHEDULED_JOBS_FULFILLED'
export const FETCH_SCHEDULED_JOBS_REJECTED =
  ROOT + 'FETCH_SCHEDULED_JOBS_REJECTED'

export const SHOW_ADD_MODAL = ROOT + 'SHOW_ADD_MODAL'
export const HIDE_ADD_MODAL = ROOT + 'HIDE_ADD_MODAL'
export const SHOW_DELETE_MODAL = ROOT + 'SHOW_DELETE_MODAL'
export const HIDE_DELETE_MODAL = ROOT + 'HIDE_DELETE_MODAL'
