export const ROOT = 'SchedulerPage/';

export const ADD_SCHEDULED_SEQUENCE = ROOT + 'ADD_SCHEDULED_SEQUENCE';
export const ADD_SCHEDULED_SEQUENCE_PENDING = ROOT + 'ADD_SCHEDULED_SEQUENCE_PENDING';
export const ADD_SCHEDULED_SEQUENCE_FULFILLED = ROOT + 'ADD_SCHEDULED_SEQUENCE_FULFILLED';
export const ADD_SCHEDULED_SEQUENCE_REJECTED = ROOT + 'ADD_SCHEDULED_SEQUENCE_REJECTED';

export const DELETE_SCHEDULED_SEQUENCE = ROOT + 'DELETE_SCHEDULED_SEQUENCE';
export const DELETE_SCHEDULED_SEQUENCE_PENDING = ROOT + 'DELETE_SCHEDULED_SEQUENCE_PENDING';
export const DELETE_SCHEDULED_SEQUENCE_FULFILLED = ROOT + 'DELETE_SCHEDULED_SEQUENCE_FULFILLED';
export const DELETE_SCHEDULED_SEQUENCE_REJECTED = ROOT + 'DELETE_SCHEDULED_SEQUENCE_REJECTED';

export const FETCH_SCHEDULED_SEQUENCES = ROOT + 'FETCH_SCHEDULED_SEQUENCES';
export const FETCH_SCHEDULED_SEQUENCES_PENDING = ROOT + 'FETCH_SCHEDULED_SEQUENCES_PENDING';
export const FETCH_SCHEDULED_SEQUENCES_FULFILLED = ROOT + 'FETCH_SCHEDULED_SEQUENCES_FULFILLED';
export const FETCH_SCHEDULED_SEQUENCES_REJECTED = ROOT + 'FETCH_SCHEDULED_SEQUENCES_REJECTED';

export const SHOW_ADD_MODAL = ROOT + 'SHOW_ADD_MODAL';
export const HIDE_ADD_MODAL = ROOT + 'HIDE_ADD_MODAL';
export const SHOW_DELETE_MODAL = ROOT + 'SHOW_DELETE_MODAL';
export const HIDE_DELETE_MODAL = ROOT + 'HIDE_DELETE_MODAL';
