export const ROOT = 'PlaylistListPage/'

export const ADD_PLAYLIST = ROOT + 'ADD_PLAYLIST'
export const ADD_PLAYLIST_PENDING = ROOT + 'ADD_PLAYLIST_PENDING'
export const ADD_PLAYLIST_FULFILLED = ROOT + 'ADD_PLAYLIST_FULFILLED'
export const ADD_PLAYLIST_REJECTED = ROOT + 'ADD_PLAYLIST_REJECTED'

export const DELETE_PLAYLIST = ROOT + 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_PENDING = ROOT + 'DELETE_PLAYLIST_PENDING'
export const DELETE_PLAYLIST_FULFILLED = ROOT + 'DELETE_PLAYLIST_FULFILLED'
export const DELETE_PLAYLIST_REJECTED = ROOT + 'DELETE_PLAYLIST_REJECTED'

export const PLAY_PLAYLIST = ROOT + 'PLAY_PLAYLIST'
export const STOP_PLAYLIST = ROOT + 'STOP_PLAYLIST'

export const FETCH_PLAYLISTS = ROOT + 'FETCH_PLAYLISTS'
export const FETCH_PLAYLISTS_PENDING = ROOT + 'FETCH_PLAYLISTS_PENDING'
export const FETCH_PLAYLISTS_FULFILLED = ROOT + 'FETCH_PLAYLISTS_FULFILLED'
export const FETCH_PLAYLISTS_REJECTED = ROOT + 'FETCH_PLAYLISTS_REJECTED'

export const SHOW_ADD_MODAL = ROOT + 'SHOW_ADD_MODAL'
export const HIDE_ADD_MODAL = ROOT + 'HIDE_ADD_MODAL'
export const SHOW_DELETE_MODAL = ROOT + 'SHOW_DELETE_MODAL'
export const HIDE_DELETE_MODAL = ROOT + 'HIDE_DELETE_MODAL'
