export const ROOT = 'PlaylistEditPage/';

export const FETCH_PLAYLISTS = ROOT + 'FETCH_PLAYLISTS';
export const FETCH_PLAYLISTS_PENDING = ROOT + 'FETCH_PLAYLISTS_PENDING';
export const FETCH_PLAYLISTS_FULFILLED = ROOT + 'FETCH_PLAYLISTS_FULFILLED';
export const FETCH_PLAYLISTS_REJECTED = ROOT + 'FETCH_PLAYLISTS_REJECTED';
