export const ROOT = 'PlaylistEditPage/';

export const FETCH_PLAYLIST = ROOT + 'FETCH_PLAYLIST';
export const FETCH_PLAYLIST_PENDING = ROOT + 'FETCH_PLAYLIST_PENDING';
export const FETCH_PLAYLIST_FULFILLED = ROOT + 'FETCH_PLAYLIST_FULFILLED';
export const FETCH_PLAYLIST_REJECTED = ROOT + 'FETCH_PLAYLIST_REJECTED';

export const FETCH_SEQUENCES = ROOT + 'FETCH_SEQUENCES';
export const FETCH_SEQUENCES_PENDING = ROOT + 'FETCH_SEQUENCES_PENDING';
export const FETCH_SEQUENCES_FULFILLED = ROOT + 'FETCH_SEQUENCES_FULFILLED';
export const FETCH_SEQUENCES_REJECTED = ROOT + 'FETCH_SEQUENCES_REJECTED';

export const SAVE_PLAYLIST = ROOT + 'SAVE_PLAYLIST';
export const SAVE_PLAYLIST_PENDING = ROOT + 'SAVE_PLAYLIST_PENDING';
export const SAVE_PLAYLIST_FULFILLED = ROOT + 'SAVE_PLAYLIST_FULFILLED';
export const SAVE_PLAYLIST_REJECTED = ROOT + 'SAVE_PLAYLIST_REJECTED';

export const ADD_PLAYLIST_SEQUENCE = ROOT + 'ADD_PLAYLIST_SEQUENCE';
export const DELETE_PLAYLIST_SEQUENCE = ROOT + 'DELETE_PLAYLIST_SEQUENCE';
export const UPDATE_PLAYLIST_SEQUENCE = ROOT + 'UPDATE_PLAYLIST_SEQUENCE';
