export const ROOT = 'SequenceListPage/'

export const ADD_SEQUENCE = ROOT + 'ADD_SEQUENCE'
export const ADD_SEQUENCE_PENDING = ROOT + 'ADD_SEQUENCE_PENDING'
export const ADD_SEQUENCE_FULFILLED = ROOT + 'ADD_SEQUENCE_FULFILLED'
export const ADD_SEQUENCE_REJECTED = ROOT + 'ADD_SEQUENCE_REJECTED'

export const DELETE_SEQUENCE = ROOT + 'DELETE_SEQUENCE'
export const DELETE_SEQUENCE_PENDING = ROOT + 'DELETE_SEQUENCE_PENDING'
export const DELETE_SEQUENCE_FULFILLED = ROOT + 'DELETE_SEQUENCE_FULFILLED'
export const DELETE_SEQUENCE_REJECTED = ROOT + 'DELETE_SEQUENCE_REJECTED'

export const FETCH_SEQUENCES = ROOT + 'FETCH_SEQUENCES'
export const FETCH_SEQUENCES_PENDING = ROOT + 'FETCH_SEQUENCES_PENDING'
export const FETCH_SEQUENCES_FULFILLED = ROOT + 'FETCH_SEQUENCES_FULFILLED'
export const FETCH_SEQUENCES_REJECTED = ROOT + 'FETCH_SEQUENCES_REJECTED'

export const SHOW_ADD_MODAL = ROOT + 'SHOW_ADD_MODAL'
export const HIDE_ADD_MODAL = ROOT + 'HIDE_ADD_MODAL'
export const SHOW_DELETE_MODAL = ROOT + 'SHOW_DELETE_MODAL'
export const HIDE_DELETE_MODAL = ROOT + 'HIDE_DELETE_MODAL'
