/***************************************************************************************************
 * This file was generated by GenerateClientTypesScript.                                           *
 * Don't edit this file manually, as it will be overwritten the next time the script is run.       *
 **************************************************************************************************/

export const ApiErrorCodeValues = [
  'ERR_AUTH_UNAUTHORIZED',
  'ERR_METHOD_NOT_ALLOWED',
  'ERR_NOT_FOUND',
  'ERR_REQUEST_CONTENT_LENGTH_EXCEEDED',
  'ERR_REQUEST_INVALID',
  'ERR_UNKNOWN',
] as const
export type ApiErrorCode = typeof ApiErrorCodeValues[number]

export type ErrorViewModel = {
  code: ApiErrorCode
  devMessage?: string
  id: string
  userMessage: string
}

export const ParamTypeValues = ['NONE', 'BOOLEAN', 'COLOR', 'COLORS', 'DECIMAL', 'INTEGER', 'STRING'] as const
export type ParamType = typeof ParamTypeValues[number]

export type Param = {
  code: string
  defaultValue: string[]
  displayName: string
  type: ParamType
}

export type PlaylistSummaryViewModel = {
  durationMs: number
  id: string
  name: string
  sequenceCount: number
}

export type Easing = {
  args: Record<string, string>
  end: number
  start: number
  type: string
}

export const BlendModeValues = ['NORMAL', 'ADD', 'SUBTRACT', 'ALPHA_MASK'] as const
export type BlendMode = typeof BlendModeValues[number]

export type Fill = {
  args: Record<string, string>
  blendMode: BlendMode
  type: string
}

export type Effect = {
  args: Record<string, string>
  easing: Easing
  endFrame: number
  fill: Fill
  id: string
  repetitionSpacing: number
  repetitions: number
  startFrame: number
  type: string
}

export type SequenceChannelViewModel = {
  displayOrder: number
  effects: Effect[]
  id: string
  name: string
  stagePropId: string
}

export const SequenceStatusValues = ['NEW', 'DRAFT', 'PUBLISHED'] as const
export type SequenceStatus = typeof SequenceStatusValues[number]

export type SequenceEditViewModel = {
  channels: SequenceChannelViewModel[]
  frameCount: number
  framesPerSecond: number
  name: string
  songId: string
  stageId: string
  status: SequenceStatus
}

export type SequenceViewModel = {
  channels: SequenceChannelViewModel[]
  frameCount: number
  framesPerSecond: number
  id: string
  name: string
  songId: string
  stageId: string
  status: SequenceStatus
}

export type SequenceSummaryViewModel = {
  durationMs: number
  framesPerSecond: number
  id: string
  name: string
  songName: string
  stageName: string
  status: SequenceStatus
}

export type Point2dViewModel = {
  x: number
  y: number
}

export const StagePropTypeValues = ['ARCH', 'LINE', 'RING', 'SPIRAL'] as const
export type StagePropType = typeof StagePropTypeValues[number]

export type StagePropViewModel = {
  brightness: number
  code: string
  displayOrder: number
  groupCode?: string
  groupDisplayOrder?: number
  id: string
  ledCount: number
  ledPositions: Point2dViewModel[]
  name: string
  positionX: number
  positionY: number
  reverse: boolean
  rotation: number
  scaleX: number
  scaleY: number
  stageId: string
  type: StagePropType
}

export const ScheduledActionTypeValues = ['NONE', 'PLAY_PLAYLIST', 'STOP_PLAYBACK', 'SET_BRIGHTNESS'] as const
export type ScheduledActionType = typeof ScheduledActionTypeValues[number]

export type ScheduledTaskSummaryViewModel = {
  cronExpression: string
  id: string
  playlistId?: string
  playlistName?: string
  type: ScheduledActionType
}

export type EditorItemViewModel = {
  code: string
  name: string
  params: Param[]
}

export type ScheduledActionEditViewModel = {
  cronExpression: string
  playlistId?: string
  type: ScheduledActionType
  value?: string
}

export type SongEditViewModel = {
  artist?: string
  durationMs: number
  name: string
}

export type StageSummaryViewModel = {
  id: string
  name: string
}

export const PlaylistActionTypeValues = ['NONE', 'PLAY_PLAYLIST', 'PLAY_SEQUENCE', 'STOP'] as const
export type PlaylistActionType = typeof PlaylistActionTypeValues[number]

export type PlaylistSequenceViewModel = {
  displayOrder: number
  id: string
  sequenceId: string
}

export type StageViewModel = {
  height: number
  id: string
  name: string
  stageProps: StagePropViewModel[]
  width: number
}

export type PlaylistViewModel = {
  id: string
  name: string
  sequences: PlaylistSequenceViewModel[]
}

export type PlaylistActionViewModel = {
  action: PlaylistActionType
  playlistId?: string
  repeat?: boolean
  sequenceId?: string
}

export type ScheduledActionViewModel = {
  cronExpression: string
  id: string
  playlistId?: string
  type: ScheduledActionType
  value?: string
}

export type SongViewModel = {
  artist?: string
  durationMs: number
  id: string
  name: string
}

export type DashboardViewModel = {
  playlists: PlaylistSummaryViewModel[]
  scheduledTasks: ScheduledTaskSummaryViewModel[]
  sequences: SequenceSummaryViewModel[]
  songs: SongViewModel[]
  stages: StageSummaryViewModel[]
}

export type SettingViewModel = {
  id: string
  value: string
}

export type ReferenceDataViewModel = {
  blendModes: EditorItemViewModel[]
  easings: EditorItemViewModel[]
  effects: EditorItemViewModel[]
  fills: EditorItemViewModel[]
}

export type SettingEditViewModel = {
  value: string
}

export type StageEditViewModel = {
  height: number
  name: string
  stageProps: StagePropViewModel[]
  width: number
}

export type PlaylistEditViewModel = {
  name: string
  sequences: PlaylistSequenceViewModel[]
}
