export const ROOT = 'StageListPage/'

export const ADD_STAGE = ROOT + 'ADD_STAGE'
export const ADD_STAGE_PENDING = ROOT + 'ADD_STAGE_PENDING'
export const ADD_STAGE_FULFILLED = ROOT + 'ADD_STAGE_FULFILLED'
export const ADD_STAGE_REJECTED = ROOT + 'ADD_STAGE_REJECTED'

export const DELETE_STAGE = ROOT + 'DELETE_STAGE'
export const DELETE_STAGE_PENDING = ROOT + 'DELETE_STAGE_PENDING'
export const DELETE_STAGE_FULFILLED = ROOT + 'DELETE_STAGE_FULFILLED'
export const DELETE_STAGE_REJECTED = ROOT + 'DELETE_STAGE_REJECTED'

export const FETCH_STAGES = ROOT + 'FETCH_STAGES'
export const FETCH_STAGES_PENDING = ROOT + 'FETCH_STAGES_PENDING'
export const FETCH_STAGES_FULFILLED = ROOT + 'FETCH_STAGES_FULFILLED'
export const FETCH_STAGES_REJECTED = ROOT + 'FETCH_STAGES_REJECTED'

export const SHOW_ADD_MODAL = ROOT + 'SHOW_ADD_MODAL'
export const HIDE_ADD_MODAL = ROOT + 'HIDE_ADD_MODAL'
export const SHOW_DELETE_MODAL = ROOT + 'SHOW_DELETE_MODAL'
export const HIDE_DELETE_MODAL = ROOT + 'HIDE_DELETE_MODAL'
