export const ROOT = 'Shared/';

export const SET_CURRENT_PAGE = ROOT + 'SET_CURRENT_PAGE';

export const FETCH_BRIGHTNESS = ROOT + 'FETCH_BRIGHTNESS';
export const FETCH_BRIGHTNESS_PENDING = ROOT + 'FETCH_BRIGHTNESS_PENDING';
export const FETCH_BRIGHTNESS_FULFILLED = ROOT + 'FETCH_BRIGHTNESS_FULFILLED';
export const FETCH_BRIGHTNESS_REJECTED = ROOT + 'FETCH_BRIGHTNESS_REJECTED';

export const UPDATE_BRIGHTNESS = ROOT + 'UPDATE_BRIGHTNESS';
export const UPDATE_BRIGHTNESS_PENDING = ROOT + 'UPDATE_BRIGHTNESS_PENDING';
export const UPDATE_BRIGHTNESS_FULFILLED = ROOT + 'UPDATE_BRIGHTNESS_FULFILLED';
export const UPDATE_BRIGHTNESS_REJECTED = ROOT + 'UPDATE_BRIGHTNESS_REJECTED';
