export const ROOT = 'SongListPage/';

export const ADD_SONG = ROOT + 'ADD_SONG';
export const ADD_SONG_PENDING = ROOT + 'ADD_SONG_PENDING';
export const ADD_SONG_FULFILLED = ROOT + 'ADD_SONG_FULFILLED';
export const ADD_SONG_REJECTED = ROOT + 'ADD_SONG_REJECTED';

export const DELETE_SONG = ROOT + 'DELETE_SONG';
export const DELETE_SONG_PENDING = ROOT + 'DELETE_SONG_PENDING';
export const DELETE_SONG_FULFILLED = ROOT + 'DELETE_SONG_FULFILLED';
export const DELETE_SONG_REJECTED = ROOT + 'DELETE_SONG_REJECTED';

export const FETCH_SONGS = ROOT + 'FETCH_SONGS';
export const FETCH_SONGS_PENDING = ROOT + 'FETCH_SONGS_PENDING';
export const FETCH_SONGS_FULFILLED = ROOT + 'FETCH_SONGS_FULFILLED';
export const FETCH_SONGS_REJECTED = ROOT + 'FETCH_SONGS_REJECTED';

export const SHOW_ADD_MODAL = ROOT + 'SHOW_ADD_MODAL';
export const HIDE_ADD_MODAL = ROOT + 'HIDE_ADD_MODAL';
export const SHOW_DELETE_MODAL = ROOT + 'SHOW_DELETE_MODAL';
export const HIDE_DELETE_MODAL = ROOT + 'HIDE_DELETE_MODAL';
